### ISSUE TITLE
Rich presence stops after a while

### ISSUE THREAD

**Issue by Team-ZzZzZ** [casheww/RW-RegionCast#15]
While I'm playing rain world, the rich presence randomly stops and either reverts to just standard rain world or discord doesn't even show I'm playing anything.

**Comment by casheww** [comment]
Hiya,
This issue is a little vague, but because I haven't added much logging to the part of the mod that works with Discord, there may not be much you can do about that, so sorry!

I have an update that *may* fix this, but I haven't gotten around to publishing it here yet, because I wanted to sort some auto-updating stuff that I haven't gotten around to yet. 
If you are in the [Rain World Discord](https://discord.gg/rainworld), the build is available [here](https://canary.discord.com/channels/291184728944410624/804088181904375819/811293690479247390) (it's my first message in the \#modding-releases channel)

Do let me know if the issue persists should you use the beta build mentioned above, thanks :)

**Comment by Team-ZzZzZ** [comment]
the beta seems to work much better for preventing the crashing

**Comment by casheww** [comment]
That's good to know - thanks for the feedback!
